### ISSUE TITLE
Sorry to bother you

### ISSUE THREAD

**Issue by shrrr** [GitJer/Some-Sipeed-MAIX-GO-k210-stuff#3]
So can you give me some advice to read and record the PCM data from the mic array? Thank you very much.

**Comment by GitJer** [comment]
Maybe this [example](https://github.com/kendryte/kendryte-standalone-demo/blob/develop/mic_play/main.c) of the [kendryte-standalone-demo](https://github.com/kendryte/kendryte-standalone-demo) can help you.

There they use a microphone as input and play the I2S signal.
